# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

ARG dist
FROM ubuntu:${dist}

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt update
RUN apt install -y libev-dev libgmp-dev libhidapi-dev libffi-dev \
                   zlib1g-dev libpq-dev m4 perl pkg-config \
                   debhelper dh-make dh-python devscripts autotools-dev \
                   python3-all python3-setuptools wget rsync cmake \
                   software-properties-common libprotobuf-dev libsqlite3-dev \
                   protobuf-compiler

ARG dist
RUN if [ "$dist" = "focal" ]; then apt-get install -y dh-systemd; fi

RUN install -m 0755 /usr/bin/python3 /usr/bin/builder

RUN add-apt-repository ppa:ubuntu-mozilla-security/rust-next -y && apt-get update -y
RUN apt-get -y install cargo opam

ENV USER dockerbuilder
RUN useradd dockerbuilder

ENV HOME /mavryk-packaging

ARG MAVKIT_VERSION
WORKDIR /mavryk-packaging/docker/sources
COPY docker/fetch_mavryk_sources.py .
RUN python3 fetch_mavryk_sources.py

WORKDIR /mavryk-packaging/docker
COPY meta.json /mavryk-packaging/meta.json
COPY protocols.json /mavryk-packaging/protocols.json
COPY docker/package/*.py /mavryk-packaging/docker/package/
COPY docker/package/defaults /mavryk-packaging/docker/package/defaults
COPY docker/package/scripts /mavryk-packaging/docker/package/scripts
COPY baking /mavryk-packaging/docker/package/baking
# Uncomment once patches are needed once again
# COPY docker/package/patches /mavryk-packaging/docker/package/patches
COPY LICENSE /mavryk-packaging/LICENSE

ENTRYPOINT ["builder", "-m", "package.package_generator"]
