# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

ARG dist
FROM fedora:${dist}

RUN dnf update -y
RUN dnf install -y libev-devel gmp-devel hidapi-devel libffi-devel \
                   zlib-devel libpq-devel m4 perl git pkg-config \
                   rpmdevtools python3-devel python3-setuptools \
                   wget opam rsync which cargo autoconf mock systemd \
                   systemd-rpm-macros cmake python3-wheel python3-tox-current-env \
                   protobuf-compiler protobuf-devel sqlite-devel

ENV USER dockerbuilder
RUN useradd dockerbuilder

ENV HOME /mavryk-packaging

WORKDIR /mavryk-packaging/docker/sources
ARG MAVKIT_VERSION
COPY docker/fetch_mavryk_sources.py .
RUN python3 fetch_mavryk_sources.py

WORKDIR /mavryk-packaging/docker
COPY meta.json /mavryk-packaging/meta.json
COPY protocols.json /mavryk-packaging/protocols.json
COPY docker/package/*.py /mavryk-packaging/docker/package/
COPY docker/package/defaults /mavryk-packaging/docker/package/defaults
COPY docker/package/scripts /mavryk-packaging/docker/package/scripts
COPY baking /mavryk-packaging/docker/package/baking
COPY LICENSE /mavryk-packaging/LICENSE

ENTRYPOINT ["python3", "-m", "package.package_generator"]
